import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/Context/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-4 py-2 flex justify-between items-center gap-5 bg-stone-800">
          <Link href={"/"}>
            <img src="/logo.png" alt="Logo" className="w-12" />
          </Link>
          <div className="space-x-5">
            <Link className="btn" href={"/foods"}>
              Foods
            </Link>
            <Link className="btn" href={"/reviews"}>
              Reviews
            </Link>
            <Link className="btn" href={""}></Link>
            <Link className="btn" href={""}></Link>
          </div>
        </header>
        <main className="px-4 py-3">
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
